apiVersion: v1
kind: Service
metadata:
  name: "game-2048"
  labels:
    app: "game-2048"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: "game-2048"
